# input_path = u"C:\Users\lmq\Desktop\biyesheji\dataset_tsmc2014\dataset_TSMC2014_NYC.txt"
dataset_path = u"C:\\Users\\lmq\\Desktop\\biyesheji\\dataset_tsmc2014\\dataset_TSMC2014_NYC.txt"
model_path = u"C:\\Users\\lmq\\Desktop\\biyesheji\\lbsn\\lbsn\\model\\parameters.json"
topn = 10
nfold = 5
iter_times = 10
polyfit_num = 50
distribution_num = 10
Fpara = 5
how_many_lines=400